### ISSUE TITLE
Fresh install: container won't start

### ISSUE THREAD

**Issue by benjamin3322** [ClemensElflein/OpenMowerOS#6]
### Issue Description:
After performing a fresh install of OpenMowerOS using the [latest release](https://github.com/ClemensElflein/OpenMowerOS/releases/download/latest/2023-08-08-1029-open-mower-os-0.1.0.zip), I encountered a container crash with the following error:

**Container Logs:**

```
Copy code
 * Starting nginx nginx                                                  [ OK ]
 * Starting network daemon: mosquitto                                    [ OK ]
... logging to /root/.ros/log/087d2002-5329-11ee-ba91-e45f01bfca97/roslaunch-openmower-80.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

RLException: environment variable 'OM_AUTOMATIC_START' is not set
The traceback for the exception was written to the log file
```

**Note:** For a first time, it was hard to know where to find the logs, i was lucky the command `sudo podman logs -f openmower` return something

**Systemctl Logs:**

```
Sep 14 19:01:53 openmower podman[2448]: 2023-09-14 19:01:53.089558281 +0100 BST m=+503.648076059 image pull
Sep 14 19:01:53 openmower podman[2448]: 2023-09-14 19:01:53.269638713 +0100 BST m=+503.828156047 container create 6edae08d74039329ef9acd4d5837e6e8c71bfd0b588a4968277e5ca0d905a9bf (image=ghcr.io/clemenselflein/open_mower_ros:releases-beta, name=openmower, org.opencontainers.image.created=2023-04-17T22:05:22.022Z, org.opencontainers.image.licenses=NOASSERTION, org.opencontainers.image.ref.name=ubuntu, org.opencontainers.image.title=open_mower_ros, org.opencontainers.image.revision=a72fb92037cca2f2b27bef120103c310f379bbc4, org.opencontainers.image.version=releases-beta, org.opencontainers.image.url=https://github.com/ClemensElflein/open_mower_ros, PODMAN_SYSTEMD_UNIT=openmower.service, io.containers.autoupdate=registry, org.opencontainers.image.source=https://github.com/ClemensElflein/open_mower_ros, org.opencontainers.image.description=)
Sep 14 19:01:53 openmower systemd[1]: Started Podman container - openmower.service.
Sep 14 19:01:57 openmower podman[2937]: 2023-09-14 19:01:57.832031295 +0100 BST m=+0.159782300 container died 6edae08d74039329ef9acd4d5837e6e8c71bfd0b588a4968277e5ca0d905a9bf (image=ghcr.io/clemenselflein/open_mower_ros:releases-beta, name=openmower)
Sep 14 19:02:03 openmower podman[2937]: 2023-09-14 19:02:03.780262135 +0100 BST m=+6.108013103 container cleanup 6edae08d74039329ef9acd4d5837e6e8c71bfd0b588a4968277e5ca0d905a9bf (image=ghcr.io/clemenselflein/open_mower_ros:releases-beta, name=openmower, PODMAN_SYSTEMD_UNIT=openmower.service, org.opencontainers.image.description=, org.opencontainers.image.title=open_mower_ros, org.opencontainers.image.version=releases-beta, org.opencontainers.image.ref.name=ubuntu, org.opencontainers.image.source=https://github.com/ClemensElflein/open_mower_ros, org.opencontainers.image.created=2023-04-17T22:05:22.022Z, org.opencontainers.image.licenses=NOASSERTION, org.opencontainers.image.revision=a72fb92037cca2f2b27bef120103c310f379bbc4, org.opencontainers.image.url=https://github.com/ClemensElflein/open_mower_ros, io.containers.autoupdate=registry)
Sep 14 19:02:03 openmower systemd[1]: openmower.service: Main process exited, code=exited, status=1/FAILURE
Sep 14 19:02:04 openmower systemd[1]: openmower.service: Failed with result 'exit-code'.
Sep 14 19:02:04 openmower systemd[1]: openmower.service: Consumed 8min 8.426s CPU time.
Sep 14 19:02:19 openmower systemd[1]: openmower.service: Scheduled restart job, restart counter is at 25.
```
This issue seems to be related to the OM_AUTOMATIC_START environment variable not being set. As a result, the container crashes during startup.

### Steps to Reproduce:

- Perform a fresh install of OpenMowerOS using the [latest release](https://github.com/ClemensElflein/OpenMowerOS/releases/download/latest/2023-08-08-1029-open-mower-os-0.1.0.zip).

- Monitor the container logs and systemctl logs for the described behavior with `sudo journalctl -fu openmower` and `sudo podman logs -f openmower`

### Expected Behavior:
The container should start successfully after the fresh install of OpenMowerOS, and the **OM_AUTOMATIC_START** variable should be set to a default value in the configuration file.

### Actual Behavior:
The container crashes during startup due to the missing **OM_AUTOMATIC_START** variable.

### Additional Information:

I use the configuration file installed on the SDCard after the Pi imager installation.
I've updated only the following with my data:

- OM_DATUM_LAT
- OM_DATUM_LONG
- OM_NTRIP_HOSTNAME
- OM_NTRIP_PORT
- OM_NTRIP_USER
- OM_NTRIP_PASSWORD
- OM_NTRIP_ENDPOINT

OpenMowerOS Release: [latest release](https://github.com/ClemensElflein/OpenMowerOS/releases/download/latest/2023-08-08-1029-open-mower-os-0.1.0.zip)

**Comment by docgalaxyblock** [comment]
The problem is known 
It downloads the default config from the main/releases-edge instead of the releses-beta branch.
A new OS version is in preperation.

**Comment by csRon** [comment]
I also ran into that issue and was able to get the container running by just adding `export OM_AUTOMATIC_START=false` into _/boot/mower_config.txt_. Don't know if that leads to other problems, but at least the container is running now.
